# tap core
tap homebrew/core
brew git
brew nodenv
brew node-build
brew tree
brew mas
brew parallel

# tap cask
tap homebrew/cask
cask visual-studio-code
cask chromium
cask firefox
cask vagrant
cask virtualbox
cask slack
cask appcleaner
cask google-japanese-ime

# tap brewfile
tap rcmdnk/file
brew brew-file

# App Store applications
appstore 425424353 The Unarchiver (4.1.0)
appstore 1278508951 Trello (2.10.14)
appstore 497799835 Xcode (10.3)
